<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
<title>Functions</title>
<link rel="stylesheet" href="../../../boostbook.css" type="text/css">
<meta name="generator" content="DocBook XSL Stylesheets V1.78.1">
<link rel="home" href="../../index.html" title="Boost.Python Reference Manual">
<link rel="up" href="../boost_python_errors_hpp.html" title="boost/python/errors.hpp">
<link rel="prev" href="class_error_already_set.html" title="Class error_already_set">
<link rel="next" href="example.html" title="Example">
</head>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF">
<table cellpadding="2" width="100%"><tr>
<td valign="top"><img alt="Boost C++ Libraries" width="277" height="86" src="../../../images/boost.png"></td>
<td align="center"><a href="../../../../index.html">Home</a></td>
<td align="center"><a href="../../../../libs/libraries.htm">Libraries</a></td>
<td align="center"><a href="http://www.boost.org/users/people.html">People</a></td>
<td align="center"><a href="http://www.boost.org/users/faq.html">FAQ</a></td>
<td align="center"><a href="../../../../more/index.htm">More</a></td>
</tr></table>
<hr>
<div class="spirit-nav">
<a accesskey="p" href="class_error_already_set.html"><img src="../../../images/prev.png" alt="Prev"></a><a accesskey="u" href="../boost_python_errors_hpp.html"><img src="../../../images/up.png" alt="Up"></a><a accesskey="h" href="../../index.html"><img src="../../../images/home.png" alt="Home"></a><a accesskey="n" href="example.html"><img src="../../../images/next.png" alt="Next"></a>
</div>
<div class="section">
<div class="titlepage"><div><div><h3 class="title">
<a name="high_level_components.boost_python_errors_hpp.functions"></a><a class="link" href="functions.html" title="Functions">Functions</a>
</h3></div></div></div>
<pre class="programlisting"><span class="keyword">template</span> <span class="special">&lt;</span><span class="keyword">class</span> <span class="identifier">T</span><span class="special">&gt;</span> <span class="keyword">bool</span> <span class="identifier">handle_exception</span><span class="special">(</span><span class="identifier">T</span> <span class="identifier">f</span><span class="special">)</span> <span class="keyword">throw</span><span class="special">();</span>
<span class="keyword">void</span> <span class="identifier">handle_exception</span><span class="special">()</span> <span class="keyword">throw</span><span class="special">();</span>
</pre>
<div class="variablelist">
<p class="title"><b></b></p>
<dl class="variablelist">
<dt><span class="term">Requires</span></dt>
<dd><p>
                The first form requires that the expression function0&lt;void&gt;(f)
                is valid. The second form requires that a C++ exception is currently
                being handled (see section 15.1 in the C++ standard).
              </p></dd>
<dt><span class="term">Effects</span></dt>
<dd><p>
                The first form calls f() inside a try block which first attempts
                to use all registered <a class="link" href="../boost_python_exception_translato.html" title="boost/python/exception_translator.hpp">exception
                translators</a>. If none of those translates the exception, the
                catch clauses then set an appropriate Python exception for the C++
                exception caught, returning true if an exception was thrown, false
                otherwise. The second form passes a function which rethrows the exception
                currently being handled to the first form.
              </p></dd>
<dt><span class="term">Postconditions</span></dt>
<dd><p>
                No exception is being handled
              </p></dd>
<dt><span class="term">Throws</span></dt>
<dd><p>
                nothing
              </p></dd>
<dt><span class="term">Rationale</span></dt>
<dd><p>
                At inter-language boundaries it is important to ensure that no C++
                exceptions escape, since the calling language usually doesn't have
                the equipment necessary to properly unwind the stack. Use handle_exception
                to manage exception translation whenever your C++ code is called
                directly from the Python API. This is done for you automatically
                by the usual function wrapping facilities: <a class="link" href="../../function_invocation_and_creation/boost_python_make_function_hpp/functions.html" title="Functions">make_function()</a>,
                <a class="link" href="../../function_invocation_and_creation/boost_python_make_function_hpp/functions.html" title="Functions">make_constructor()</a>,
                <a class="link" href="../boost_python_def_hpp/functions.html" title="Functions">def()</a>
                and <a class="link" href="../../high_level_components.html#high_level_components.boost_python_class_hpp.class_template_class_t_bases_hel.class_template_class_modifier_fu" title="Class template class_ modifier functions">class_::def()</a>.
                The second form can be more convenient to use (see the example below),
                but various compilers have problems when exceptions are rethrown
                from within an enclosing try block.
              </p></dd>
</dl>
</div>
<pre class="programlisting"><span class="keyword">template</span> <span class="special">&lt;</span><span class="keyword">class</span> <span class="identifier">T</span><span class="special">&gt;</span> <span class="identifier">T</span><span class="special">*</span> <span class="identifier">expect_non_null</span><span class="special">(</span><span class="identifier">T</span><span class="special">*</span> <span class="identifier">x</span><span class="special">);</span></pre>
<div class="variablelist">
<p class="title"><b></b></p>
<dl class="variablelist">
<dt><span class="term">Returns</span></dt>
<dd><p>
                x
              </p></dd>
<dt><span class="term">Throws</span></dt>
<dd><p>
                error_already_set() iff x == 0.
              </p></dd>
<dt><span class="term">Rationale</span></dt>
<dd><p>
                Simplifies error-handling when calling functions in the Python/C
                API which return 0 on error.
              </p></dd>
</dl>
</div>
<pre class="programlisting"><span class="keyword">void</span> <span class="identifier">throw_error_already_set</span><span class="special">();</span></pre>
<div class="variablelist">
<p class="title"><b></b></p>
<dl class="variablelist">
<dt><span class="term">Effects</span></dt>
<dd><p>
                throw error_already_set();
              </p></dd>
<dt><span class="term">Rationale</span></dt>
<dd><p>
                Simplifies error-handling when calling functions in the Python/C
                API which return 0 on error.
              </p></dd>
</dl>
</div>
<pre class="programlisting"><span class="keyword">void</span> <span class="identifier">throw_error_already_set</span><span class="special">();</span></pre>
<div class="variablelist">
<p class="title"><b></b></p>
<dl class="variablelist">
<dt><span class="term">Effects</span></dt>
<dd><p>
                throw error_already_set();
              </p></dd>
<dt><span class="term">Rationale</span></dt>
<dd><p>
                Many platforms and compilers are not able to consistently catch exceptions
                thrown across shared library boundaries. Using this function from
                the Boost.Python library ensures that the appropriate catch block
                in handle_exception() can catch the exception.
              </p></dd>
</dl>
</div>
</div>
<table xmlns:rev="http://www.cs.rpi.edu/~gregod/boost/tools/doc/revision" width="100%"><tr>
<td align="left"></td>
<td align="right"><div class="copyright-footer">Copyright &#169; 2002-2005, 2015 David Abrahams, Stefan Seefeld<p>
        Distributed under the Boost Software License, Version 1.0. (See accompanying
        file LICENSE_1_0.txt or copy at <a href="http://www.boost.org/LICENSE_1_0.txt" target="_top">http://www.boost.org/LICENSE_1_0.txt</a>
      </p>
</div></td>
</tr></table>
<hr>
<div class="spirit-nav">
<a accesskey="p" href="class_error_already_set.html"><img src="../../../images/prev.png" alt="Prev"></a><a accesskey="u" href="../boost_python_errors_hpp.html"><img src="../../../images/up.png" alt="Up"></a><a accesskey="h" href="../../index.html"><img src="../../../images/home.png" alt="Home"></a><a accesskey="n" href="example.html"><img src="../../../images/next.png" alt="Next"></a>
</div>
</body>
</html>
